# Generated by Django 3.2.6 on 2021-09-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detailed_address', models.CharField(max_length=1200, null=True)),
                ('baranggay', models.CharField(max_length=300, null=True)),
                ('city', models.CharField(max_length=300, null=True)),
                ('province', models.CharField(max_length=300, null=True)),
                ('region', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
