# Generated by Django 3.2.6 on 2021-09-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='number_street_subd',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
