# Generated by Django 3.2.6 on 2021-09-09 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_address_number_street_subd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='baranggay',
            new_name='city_town',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='city',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='number_street_subd',
            new_name='state_province_area',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='province',
            new_name='street',
        ),
        migrations.RemoveField(
            model_name='address',
            name='detailed_address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='region',
        ),
    ]
