# Generated by Django 3.2.6 on 2021-09-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_auto_20210909_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='city_town',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='state_province_area',
            new_name='province',
        ),
        migrations.AddField(
            model_name='address',
            name='barangay',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='region',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
