# Generated by Django 3.2.6 on 2021-10-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0004_auto_20210930_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='barangay_code',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='city_code',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='country_code',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='province_code',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='region_code',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
