# Generated by Django 3.2.6 on 2021-10-04 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0006_remove_address_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='country_code',
        ),
    ]
