# Generated by Django 3.2.6 on 2021-10-11 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transaction_items', '0018_transaction_item_review'),
        ('transactions', '0043_transaction_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_condition', models.FileField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_refunds', to='transactions.transaction')),
                ('transaction_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_item_refunds', to='transaction_items.transaction_item')),
            ],
        ),
    ]
