# Generated by Django 3.2.6 on 2021-10-12 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0043_transaction_order_status'),
        ('transaction_items', '0018_transaction_item_review'),
        ('refunds', '0002_transaction_item_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction_item',
            new_name='Refund',
        ),
    ]
