# Generated by Django 3.2.6 on 2021-10-12 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('refunds', '0003_rename_transaction_item_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_refunds', to=settings.AUTH_USER_MODEL),
        ),
    ]
