# Generated by Django 3.2.6 on 2021-10-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refunds', '0005_rename_product_condition_refund_product_condition_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='transaction',
        ),
        migrations.AddField(
            model_name='refund',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
