# Generated by Django 3.2.6 on 2021-10-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refunds', '0006_auto_20211013_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
