# Generated by Django 3.1.3 on 2020-12-10 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='stock',
        ),
    ]
