# Generated by Django 3.1.3 on 2020-12-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0002_remove_inventory_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='stock_added',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
