# Generated by Django 3.1.3 on 2020-12-10 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0003_inventory_stock_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='stock_added',
            new_name='new_stock',
        ),
    ]
