# Generated by Django 3.2 on 2021-06-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0004_auto_20201210_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='inventory_id',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
