# Generated by Django 3.2 on 2021-07-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0005_inventory_inventory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='inventory_id',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
