# Generated by Django 3.2.6 on 2021-09-06 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_variations', '0001_initial'),
        ('inventories', '0008_alter_inventory_inventory_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='product_with_variation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_with_variation_inventory_set', to='product_variations.product_variation'),
        ),
    ]
