# Generated by Django 3.2.6 on 2021-10-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0009_inventory_product_with_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
