# Generated by Django 3.2.6 on 2021-10-15 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0010_inventory_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='inventory_id',
        ),
    ]
