# Generated by Django 3.1.3 on 2020-12-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='totalAmount',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
