# Generated by Django 3.1.3 on 2020-12-20 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_totalamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 21, 1, 16, 10, 302265)),
        ),
    ]
