# Generated by Django 3.1.3 on 2020-12-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20201221_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount_tendered',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='change',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
