# Generated by Django 3.1.5 on 2021-01-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20201221_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='totalAmount',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
