# Generated by Django 3.2 on 2021-06-25 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0014_transaction_creator_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='creator_account',
        ),
        migrations.AddField(
            model_name='transaction',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_transaction', to=settings.AUTH_USER_MODEL),
        ),
    ]
