# Generated by Django 3.2 on 2021-06-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_auto_20210625_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
