# Generated by Django 3.2 on 2021-06-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_transaction_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='mode_of_payment',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
