# Generated by Django 3.2.6 on 2021-08-21 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0022_alter_transaction_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('shipment_details', models.CharField(max_length=255)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_transaction', to='transactions.transaction')),
            ],
        ),
    ]
