# Generated by Django 3.2.6 on 2021-08-25 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0023_onlinetransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlinetransaction',
            old_name='shipment_details',
            new_name='shipping_details',
        ),
    ]
