# Generated by Django 3.2.6 on 2021-08-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0024_rename_shipment_details_onlinetransaction_shipping_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='mode_of_payment',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
