# Generated by Django 3.2.6 on 2021-08-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0025_alter_transaction_mode_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinetransaction',
            name='shipping_details',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
