# Generated by Django 3.2.6 on 2021-08-25 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0027_alter_transaction_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinetransaction',
            name='transaction',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='online_transaction', to='transactions.transaction'),
        ),
    ]
