# Generated by Django 3.2.6 on 2021-08-28 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0030_alter_transaction_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlinetransaction',
            old_name='transaction',
            new_name='_transaction_id',
        ),
    ]
