# Generated by Django 3.2.6 on 2021-08-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0033_auto_20210829_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='shipping_details',
            new_name='address',
        ),
        migrations.AddField(
            model_name='transaction',
            name='contact_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
