# Generated by Django 3.2.6 on 2021-09-16 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0035_auto_20210916_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='address',
            field=models.CharField(blank=True, max_length=655, null=True),
        ),
    ]
