# Generated by Django 3.2.6 on 2021-09-16 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0036_alter_transaction_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='mode_of_payment',
            new_name='payment_method',
        ),
    ]
