# Generated by Django 3.2.6 on 2021-09-16 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0037_rename_mode_of_payment_transaction_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='change',
        ),
    ]
