# Generated by Django 3.2.6 on 2021-09-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_items', '0017_transaction_item_product_with_variation'),
        ('transactions', '0039_remove_transaction_amount_tendered'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, related_name='transaction_item', to='transaction_items.Transaction_item'),
        ),
    ]
