# Generated by Django 3.2.6 on 2021-10-04 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0042_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='order_status',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
