# Generated by Django 3.2.6 on 2021-10-15 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0043_transaction_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_id',
        ),
    ]
