# Generated by Django 3.2.6 on 2021-10-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0044_remove_transaction_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
