# Generated by Django 3.2.6 on 2021-11-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0045_transaction_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='shippingCost',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
