# Generated by Django 3.2 on 2021-07-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
