# Generated by Django 3.1.3 on 2020-11-29 16:25

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_currency',
             field=models.IntegerField(default=21),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=21),
        ),
    ]
