# Generated by Django 3.1.5 on 2021-01-15 15:28

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='No-Image-Available.jpeg', force_format=None, keep_meta=True, null=True, quality=0, size=[600, 410], upload_to=''),
        ),
    ]
