# Generated by Django 3.2 on 2021-08-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_files', '0003_auto_20210810_1839'),
        ('products', '0019_alter_product_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='file_content',
            field=models.ManyToManyField(blank=True, null=True, related_name='file_content', to='product_files.Product_file'),
        ),
    ]
