# Generated by Django 3.2 on 2021-08-12 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_product_file_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='file_content',
        ),
    ]
