# Generated by Django 3.2.6 on 2021-08-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_files', '0009_remove_product_file_product'),
        ('products', '0026_product_file_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file_content',
            field=models.ManyToManyField(blank=True, related_name='file_content', to='product_files.Product_file'),
        ),
    ]
