# Generated by Django 3.2.6 on 2021-09-04 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_product_status'),
    ]

    operations = [
       
    ]
