# Generated by Django 3.2.6 on 2021-09-04 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_auto_20210904_2337'),
    ]

    operations = [
     
    ]
