# Generated by Django 3.2.6 on 2021-09-04 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_auto_20210904_2339'),
    ]

    operations = [
      
    ]
