# Generated by Django 3.2.6 on 2021-09-04 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_remove_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
