# Generated by Django 3.2.6 on 2021-09-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_variations', '0001_initial'),
        ('products', '0033_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variation',
            field=models.ManyToManyField(blank=True, null=True, related_name='variation_product', to='product_variations.Product_variation'),
        ),
    ]
