# Generated by Django 3.2.6 on 2021-09-15 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_product_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='media',
            field=models.FileField(blank=True, default='No-Image-Available.jpeg', null=True, upload_to=''),
        ),
    ]
