# Generated by Django 3.2.6 on 2021-09-15 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_product_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='media',
        ),
    ]
