# Generated by Django 3.2.6 on 2021-09-18 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_remove_product_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
