# Generated by Django 3.2.6 on 2021-11-02 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_product_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
    ]
