# Generated by Django 3.2 on 2021-08-09 12:43

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0019_alter_product_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='No-Image-Available.jpeg', force_format=None, keep_meta=True, null=True, quality=0, size=[1200, 820], upload_to='')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_file_set', to='products.product')),
            ],
        ),
    ]
