# Generated by Django 3.2 on 2021-08-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_files', '0002_alter_product_file_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_file',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product_file',
            name='product',
        ),
        migrations.AddField(
            model_name='product_file',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
