# Generated by Django 3.2 on 2021-08-12 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_files', '0004_auto_20210810_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_file',
            name='product',
        ),
    ]
