# Generated by Django 3.2.6 on 2021-09-15 02:58

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('product_files', '0009_remove_product_file_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_file',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='No-Image-Available.jpeg', force_format=None, keep_meta=True, null=True, quality=0, size=[1200, 820], upload_to=''),
        ),
    ]
