# Generated by Django 3.2.6 on 2021-09-15 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_files', '0011_alter_product_file_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_file',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
