# Generated by Django 3.2.6 on 2021-09-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0002_remove_voucher_claimed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='claimed_date',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='valid_till',
        ),
        migrations.AddField(
            model_name='voucher',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
