# Generated by Django 3.2.6 on 2021-10-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0003_auto_20210919_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
