# Generated by Django 3.2.6 on 2021-09-18 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_variations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_variation',
            name='product',
        ),
    ]
