# Generated by Django 3.2 on 2021-07-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities_log', '0003_alter_log_activity_activity_log_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_activity',
            name='activity_log_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
