# Generated by Django 3.2.6 on 2021-10-15 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities_log', '0004_alter_log_activity_activity_log_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log_activity',
            name='activity_log_id',
        ),
    ]
