# Generated by Django 3.2 on 2021-06-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_log',
            name='attendance_log_id',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
