# Generated by Django 3.2 on 2021-07-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_log', '0007_alter_attendance_log_attendance_log_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_log',
            name='logout_at',
            field=models.DateTimeField(null=True),
        ),
    ]
