# Generated by Django 3.2.6 on 2021-10-15 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_log', '0008_alter_attendance_log_logout_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance_log',
            name='attendance_log_id',
        ),
    ]
