# Generated by Django 3.2.6 on 2021-08-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address_id',
            field=models.ManyToManyField(blank=True, related_name='account_address', to='accounts.Address'),
        ),
        migrations.AlterField(
            model_name='account',
            name='contact_number_id',
            field=models.ManyToManyField(blank=True, related_name='account_contact_number', to='accounts.Address'),
        ),
    ]
