# Generated by Django 3.2.6 on 2021-09-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_contact_number_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address_id',
            field=models.ManyToManyField(blank=True, null=True, related_name='account_address', to='accounts.Address'),
        ),
        migrations.AlterField(
            model_name='account',
            name='contact_number_id',
            field=models.ManyToManyField(blank=True, null=True, related_name='account_contact_number', to='accounts.Contact_number'),
        ),
    ]
