# Generated by Django 3.2.6 on 2021-09-08 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210908_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='address_id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='contact_number_id',
        ),
    ]
