# Generated by Django 3.2.6 on 2021-09-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('contact_numbers', '0001_initial'),
        ('accounts', '0006_auto_20210909_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address_id',
            field=models.ManyToManyField(blank=True, null=True, related_name='account_address', to='addresses.Address'),
        ),
        migrations.AddField(
            model_name='account',
            name='contact_number_id',
            field=models.ManyToManyField(blank=True, null=True, related_name='account_contact_number', to='contact_numbers.Contact_number'),
        ),
    ]
