# Generated by Django 3.2.6 on 2021-09-08 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210909_0126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='address_id',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='contact_number_id',
            new_name='contact_number',
        ),
    ]
