# Generated by Django 3.2.6 on 2021-09-11 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_auto_20210909_1606'),
        ('accounts', '0008_auto_20210909_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='address',
        ),
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_address', to='addresses.address'),
        ),
        migrations.RemoveField(
            model_name='account',
            name='contact_number',
        ),
        migrations.AddField(
            model_name='account',
            name='contact_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
