# Generated by Django 3.1.3 on 2020-12-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction_item',
            name='product',
        ),
        migrations.RemoveField(
            model_name='transaction_item',
            name='transaction',
        ),
        migrations.AddField(
            model_name='transaction_item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='transaction_item',
            name='product_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transaction_item',
            name='product_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
