# Generated by Django 3.1.3 on 2020-12-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_items', '0002_auto_20201213_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_item',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
