# Generated by Django 3.1.3 on 2020-12-14 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20201210_1701'),
        ('transaction_items', '0003_auto_20201213_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction_item',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='transaction_item',
            name='product_name',
        ),
        migrations.AddField(
            model_name='transaction_item',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_transaction_item_set', to='products.product'),
        ),
    ]
