# Generated by Django 3.1.3 on 2020-12-14 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_items', '0004_auto_20201214_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction_item',
            old_name='product',
            new_name='productx',
        ),
    ]
