# Generated by Django 3.1.3 on 2020-12-15 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_items', '0005_auto_20201215_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction_item',
            old_name='productx',
            new_name='product',
        ),
    ]
