# Generated by Django 3.1.3 on 2020-12-15 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_items', '0006_auto_20201215_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_item',
            name='prod_id',
            field=models.IntegerField(null=True),
        ),
    ]
