# Generated by Django 3.1.3 on 2020-12-16 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_items', '0007_transaction_item_prod_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction_item',
            name='prod_id',
        ),
    ]
