# Generated by Django 3.1.3 on 2020-12-18 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_items', '0009_transaction_item_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction_item',
            name='price',
        ),
    ]
