# Generated by Django 3.1.3 on 2020-12-19 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_totalamount'),
        ('transaction_items', '0011_auto_20201219_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_item',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_set', to='transactions.transaction'),
        ),
    ]
