# Generated by Django 3.2 on 2021-06-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_items', '0012_auto_20201219_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_item',
            name='transaction_item_id',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
