# Generated by Django 3.2.6 on 2021-09-26 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_rename_reveiew_review'),
        ('transaction_items', '0017_transaction_item_product_with_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_item',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_item_review', to='reviews.review'),
        ),
    ]
