# Generated by Django 3.2.6 on 2021-10-13 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refunds', '0006_auto_20211013_2049'),
        ('transaction_items', '0018_transaction_item_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_item',
            name='refund',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_item_refund', to='refunds.refund'),
        ),
    ]
