# Generated by Django 3.2.6 on 2021-10-15 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_items', '0019_transaction_item_refund'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction_item',
            name='transaction_item_id',
        ),
    ]
