# Generated by Django 3.2 on 2021-06-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_auto_20210119_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='supplier_id',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
