# Generated by Django 3.2 on 2021-07-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_supplier_supplier_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplier_id',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
