# Generated by Django 3.2.6 on 2021-08-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0006_alter_supplier_supplier_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='status',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
