# Generated by Django 3.2.6 on 2021-09-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0007_supplier_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
