# Generated by Django 3.2.6 on 2021-10-15 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0008_alter_supplier_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='supplier_id',
        ),
    ]
